version: '3.8'

services:
  mongo:
    image: mongo:5.0.9
    restart: always
    volumes:
      - ./database/storage/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: maindb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-db:
    image: node:18-slim
    working_dir: /app
    env_file:
      - ./backend/.env
    environment:
      - DB_URL=mongodb://mongo:27017
    volumes:
      - ./backend:/app
    depends_on:
      mongo:
        condition: service_healthy
    command: >
      sh -c "
        node helpers/populateCities.js &&
        node helpers/populateCoordinates.js
      "

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      mongo:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_started
