FROM node:slim

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@latest-10

COPY ./package.json ./pnpm-lock.yaml ./

RUN pnpm install

COPY . .

ENTRYPOINT ["./entrypoint.sh"]